setwd("C:/Users/Mit3vK3y/Desktop/MONJAS/analisis de datos") 
datos4<-read.table("datos dientes limpios promedio.csv", header=TRUE, sep=";",na.strings="NA",
                  fileEncoding = "UTF-8",
                  quote = "\"",
                  colClasses=c(rep("character",3),
                               rep("numeric",12)
                               )
                  )
datos3<-datos2[1:20,];

install.packages("factoextra")
library(factoextra) # You can use this package for data visualisation 

pca1 <- prcomp(datos4[,10:12], retx=TRUE, center=T, scale=T) 
predicted <-predict(pca1,datos4[,10:12])

fviz_eig(pca1, addlabels = T) # Percentage of variance explained by each PC
fviz_pca_ind(pca1, label="none", habillage=datos$muestra, axes = c(1,2)) # Samples/Scores plot (new coordinates)


fviz_pca_var(pca1, geom = c("point", "text"), repel = T) # Variables/correlations plot (correlations between variables and PC)
# Let's do a variable/loadings plot (loadings = coefficients of the PCs,
# which are lineal combinations of the original variable. 
col.pc1 <- ifelse(pca1$rotation[,1] > 0, yes = "green", no = "red")
col.pc2 <- ifelse(pca1$rotation[,2] > 0, yes = "green", no = "red")
b1 <- barplot(pca1$rotation[,1], main = "Cargas PC1", col = col.pc1, axisname = F)
text(b1, y=ifelse(pca1$rotation[,1] > 0, -0.01, pca1$rotation[,1] -0.01),
     labels=names(pca1$rotation[,1]), adj=1, srt=90, xpd=T, cex = 0.8)
b2 <- barplot(pca1$rotation[,2], main = "Cargas PC2", col = col.pc2, las = 2, axisname = F)
text(b1, y=ifelse(pca1$rotation[,2] > 0, -0.01, pca1$rotation[,2] -0.01),
     labels=names(pca1$rotation[,2]), adj=1, srt=90, xpd=NA, cex = 0.7)

ggplot(data.frame(predicted))+
  aes(x=PC1,y=PC2,color=datos4$pink,label = datos4$diente, label.size = 3)+
  geom_point(aes(shape=datos4$pink),size = 4)+
  geom_text(hjust=1.3, vjust=0)+
  #stat_ellipse()+
  #stat_ellipse(palette="Set3",level=0.,geom = "polygon",alpha = 1/10, aes(fill = datos2$estado))+
  theme_bw() +
  theme(
    panel.grid.major = element_line(colour = "grey95", size = 0.2),
    panel.grid.minor = element_blank(),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12)
  )+
  geom_vline(xintercept=0,linetype=2) +
  geom_hline(yintercept=0, linetype=2)+  
  scale_x_continuous(name="Dim1",breaks = seq(-5,5,by=1), limits=c(-5, 5)) +
  scale_y_continuous(name="Dim2",breaks = seq(-3,2,by=1), limits=c(-3,2))
  #scale_color_brewer(palette="Paired")+
  #scale_fill_brewer(palette="Paired")